[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
protocol = { path = "../protocol" }
nix = { version = "0.29", features = ["ioctl", "fs"] }
libc = "0.2"
rand = "0.8"
crossbeam-channel = "0.5"
snow = "0.10"
hex = "0.4"
byteorder = "1"
